theme: jekyll-theme-cayman
title: Vogelradar - Vogelsichtungen interaktiv erkunden
image: "/assets/Screenshot_App.png"
# description: Speichere diese Seite als Bookmark und verfolge unseren Projektstand!
